реализация действий по кнопке
ekafila/REACT-APP-FILA pull request #3
Opened 2021-04-30 17:30 UTC by ekafila

Екатерина Филюгина
Я смогла сделать реализацию кнопок и input (визуально), но не получается реализовать вставку написанного в input в список и менять состояние completed при щелчке на checkbox. Мои попытки создать эти функции находятся в комментарии в файле ./src/App.js

2021-05-02 21:07 UTC, ekafila commented
Я разделила программу, и написала функцию для внесения изменений в список (MyTodoList.js), но не смогла пока что справиться с ошибкой "Can't call setState on a component that is not yet mounted..." 
Галочка в checkbox не меняет состояние Completed. Я думала сделать это через функцию в Task. Примерная идея закомментирована в Task.js

2021-05-08 11:00 UTC, ValeryStatinov requested changes
ну, дз еще не закончено:( обращайся в случае трудностями с вопросами ко мне, а лучше в общий чат

2021-05-08 11:00 UTC, ValeryStatinov commented on src/App.js
> +      <button onClick={new MyTodoList().handleClick}>Add</button>
не создаем компоненты через new

2021-05-08 11:00 UTC, ValeryStatinov commented on src/MyTodoList/MyTodoList.js
> +            const description = TaskAdd.state.description
nope:(
пусть `handleClick` получает значения name и description в кач-ве аргументов. компонент `TaskAdd` получит эту ф-ию в кач-ве пропа и будет вызывать при клике на кнопку ADD таким обзаром: `onClick={() => this.props.handleClick(this.state.name, this.state.description)`

2021-05-08 11:00 UTC, ValeryStatinov commented on src/Task/Task.js
> +        {/* <button className='complete-button' onClick={() => TaskLog(id, completed)}>Completed</button> */}
для смены статуса нужно здесь вызыват ф-ию, полученную через props и передавать ей id таски, на которую нажали

2021-05-10 21:05 UTC, ekafila commented
После долгого общения и помощи со стороны ребят и сторонних источников (форумы и тд) все заработало! Теперь логика выполняется: новая задача добавляется, статус меняется на выполненный. 
Для меня эта задача оказалась настоящим вызовом :)

2021-05-12 09:41 UTC, ValeryStatinov approved these changes
теперь все хорошо) отл(8)

2021-05-12 09:41 UTC, ValeryStatinov commented on src/App.js
> +// }
ето можно удалять)

2021-05-12 09:41 UTC, ValeryStatinov commented on src/MyTodoList/MyTodoList.js
> +        this.setState({[name]: value})
изначально в стейте нет полей `name` и `description`, лучше их проинициализовать там пустыми строками

2021-05-12 09:43 UTC, ValeryStatinov commented
здорово, что получилось разобраться! и здорово, что обращалась за помощью к ребятам:)
в случае возникновения трудностей можешь также задавать вопросы мне, в общий чат или на семинарах

2021-05-12 09:43 UTC, merged

2021-05-12 09:45 UTC, ValeryStatinov commented
ой, только в конце заметил, что PR hw4 -> hw3
нужно все это смерджить в мастер и новую ветку для след дз делать от мастера